version: 2
models:
  - name: fct_player_season_stats
    description: "**Business Summary:**\n\nThe business summary of the model explanation\
      \ is that it creates a database model to calculate various statistics for basketball\
      \ players. The model retrieves data from two sources, aggregates player statistics,\
      \ and joins it with salary information. The resulting statistics can be used\
      \ to analyze and compare the performance and value of basketball players based\
      \ on their salaries and on-court contributions.\n\n**Technical Summary:**\n\n\
      The dbt model shown above is used to calculate various statistics for basketball\
      \ players. It starts by gathering data from two sources: `source_player_game_logs`\
      \ and `source_player_salaries`.\n\nThe model creates a temporary table called\
      \ `playerstats` that aggregates player statistics, such as total minutes played,\
      \ field goals made, three-pointers made, free throws made, rebounds, assists,\
      \ turnovers, steals, blocks, personal fouls, points, and several others. These\
      \ statistics are calculated by summing up the corresponding values for each\
      \ player.\n\nAfter calculating the statistics, the model joins the `playerstats`\
      \ table with the `source_player_salaries` table using the player's name as the\
      \ matching column. This allows the model to retrieve the salary information\
      \ for each player.\n\nThe final select statement in the model retrieves the\
      \ player ID, player name, salary for the 2022-23 season, total minutes played,\
      \ salary per minute played, salary per game played, average field goal percentage,\
      \ average three-point percentage, average free throw percentage, total assists,\
      \ average assists per game, total turnovers, average turnovers per game, total\
      \ steals, total blocks, total block attempts, total personal fouls, total personal\
      \ fouls drawn, total points, average points per game, total plus-minus, and\
      \ average plus-minus.\n\nThese statistics can be used to analyze and compare\
      \ the performance and value of basketball players based on their salaries and\
      \ various on-court contributions."
    columns:
      - name: PLAYER_ID
        description: The unique id of an nba player
      - name: PLAYER_NAME
        description: The full name of an nba player
      - name: 2022_23_salary
        description: 'the 2022-23 salary of an nba player '
      - name: TOTAL_MINS_PLAYED
        description: the total minutes played by an NBA player during the 2022-23
          nba season
      - name: SALARY_PER_MINUTE_PLAYED
        description: The salary per minute played during the 2022-23 NBA season
      - name: SALARY_PER_GAME_PLAYED
        description: The avg. salary per hame played during the 2022-23 nba season
      - name: AVG_FIELD_GOAL_PCT
        description: The avg. field goal percentage for an nba player during the 2022-23
          nba season
      - name: AVG_THREE_POINT_PCT
        description: The avg. 3 points field goal percentage for an nba player during
          the 2022-23 nba season
      - name: AVG_FREE_THROW_PCT
        description: the avg free throw percentage for an nba player during the 2022-23
          nba season
      - name: TOTAL_ASSISTS
        description: the total assists for an nba player during the 2022-23 nba season
      - name: AVG_ASSISTS_PER_GAME
        description: the averages assists per game for an nba player during the 2022-23
          nba season
      - name: TOTAL_TURNOVERS
        description: the total turnovers for an nba player during the 2022-23 nba
          season
      - name: AVG_TURNOVERS_PER_GAME
        description: the average turnoers per game for an nba player during the 2022-23
          nba season
      - name: TOTAL_STEALS
        description: the total steals for an nba player during the 2022-23 nba season
      - name: TOTAL_BLOCKS
        description: the total blocks for an nba player during the 2022-23 nba season
      - name: TOTAL_BLOCK_ATTEMPTS
        description: the total blocks attempted for an nba player during the 2022-23
          nba season
      - name: TOTAL_PERSONAL_FOULS
        description: the total personal fouls committed for an nba player during the
          2022-23 nba season
      - name: TOTAL_PERSONAL_FOUL_DRAWN
        description: the total personal fouls drawn for an nba player during the 2022-23
          nba season
      - name: TOTAL_POINTS
        description: the total points scored for an nba player during the 2022-23
          nba season
      - name: AVG_POINTS_PER_GAME
        description: the points per game for an nba player during the 2022-23 nba
          season
      - name: TOTAL_PLUS_MINUS
        description: the total plus minus for an nba player during the 2022-23 nba
          season
      - name: AVERAGE_PLUS_MINUS
        description: the average plus minus for an nba player during the 2022-23 nba
          season
