version: 2
models:
  - name: intermediate_game_date_details
    description: "**Business Summary:**\n\nThe business summary of the model explanation\
      \ is that this model is used to rank and categorize games by team, game date,\
      \ season quarter, and season month. It uses a common table expression (CTE)\
      \ to rank the games and calculates the season month using the month() function.\
      \ The main query selects the relevant columns from the CTE and uses CASE statements\
      \ to determine the season quarter and season month.\n\n**Technical Summary:**\n\
      \nThe dbt model is using a common table expression (CTE) called `ranked_games`\
      \ to rank the games by team_id and game_date. The CTE selects the team_id, game_id,\
      \ team_name, game_date, and calculates the season_month using the month() function.\
      \ It also assigns a game_rank to each game within a team, ordered by game_date\
      \ and game_id.\n\nThen, the main query selects the team_id, game_id, team_name,\
      \ game_rank, game_date from the ranked_games CTE. It also uses a CASE statement\
      \ to determine the season_quarter based on the game_rank, and assigns a value\
      \ from 1 to 4.\n\nAnother CASE statement is used to determine the season_month\
      \ based on the season_month calculated in the CTE, and assigns a value from\
      \ 1 to 7 based on the month.\n\nOverall, this model is used to rank and categorize\
      \ the games by team, game date, season quarter, and season month."
  - name: intermediate_player_salaries
    description: "**Business Summary:**\n\nThe business summary of the model explanation\
      \ is that it fetches data from the `source_player_salaries` table and filters\
      \ out rows where the `2022_23_salary` column has a null value.\n\n**Technical\
      \ Summary:**\n\nThe dbt model begins by creating a CTE (common table expression)\
      \ called `source` which selects all columns from the dbt source table named\
      \ `source_player_salaries`. \n\nThen, the model selects all columns from the\
      \ `source` CTE and applies a filter using the WHERE clause. It only includes\
      \ rows where the value of the column `2022_23_salary` is not null. \n\nIn summary,\
      \ the dbt model is fetching data from the `source_player_salaries` table and\
      \ only returning rows that have a non-null value in the `2022_23_salary` column."
  - name: intermediate_player_game_logs
    description: "**Business Summary:**\n\nThe business summary of the model explanation\
      \ is that the dbt model creates temporary tables, performs data joins, and selects\
      \ specific columns to return a result.\n\n**Technical Summary:**\n\nThe dbt\
      \ model starts by creating a temporary table called `season_quarters` which\
      \ contains the data from the `intermediate_game_date_details` table. \n\nNext,\
      \ another temporary table called `player_game_logs` is created which contains\
      \ the data from the `source_player_game_logs` table.\n\nThen, a final temporary\
      \ table called `joined` is created by joining the `player_game_logs` table with\
      \ the `season_quarters` table on the conditions that the game date and team\
      \ id match.\n\nFinally, the query selects all columns from the `joined` table\
      \ and returns the result."
